version: '3'

services:
  agile-planner-mcp:
    build: .
    image: agile-planner-mcp-server:latest
    volumes:
      - ./output:/app/.agile-planner-backlog
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Décommenter pour utiliser GROQ au lieu de OpenAI
      # - GROQ_API_KEY=${GROQ_API_KEY}
      # Mode d'exécution : MCP ou CLI
      - MCP_EXECUTION=${MCP_EXECUTION:-false}
      - AGILE_PLANNER_OUTPUT_ROOT=/app/.agile-planner-backlog
    # En mode interactif par défaut pour l'utilisation CLI
    stdin_open: true
    tty: true
