version: '3'

services:
  agile-planner:
    build: .
    volumes:
      - ./output:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Décommenter pour utiliser GROQ au lieu de OpenAI
      # - GROQ_API_KEY=${GROQ_API_KEY}
    # En mode interactif par défaut
    stdin_open: true
    tty: true
